name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        target:
          - Linux
          - Windows
          - Darwin
          - Linux-ASan-Coverage
        include:
          - target: Linux
            os: ubuntu-latest
            artifact: linux64
            out_dir: Linux
            build_script: build.sh
            cmake_args: ""

          - target: Windows
            os: windows-latest
            artifact: win64
            out_dir: Windows
            build_script: build.ps1
            cmake_args: ""

          - target: Darwin
            os: macos-latest
            artifact: macos64
            out_dir: Darwin
            build_script: build.sh
            cmake_args: "-DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DSPIRV_WERROR=OFF -DSWIFTSHADER_WARNINGS_AS_ERRORS=OFF"

          - target: Linux-ASan-Coverage
            os: ubuntu-latest
            artifact: linux64-asan-coverage
            out_dir: Linux
            build_script: build.sh
            cmake_args: '-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DSWIFTSHADER_ASAN=ON -DSWIFTSHADER_WARNINGS_AS_ERRORS=OFF -DCMAKE_C_FLAGS="-fprofile-instr-generate -fcoverage-mapping" -DCMAKE_CXX_FLAGS="-fprofile-instr-generate -fcoverage-mapping" -DCMAKE_EXE_LINKER_FLAGS="-fprofile-instr-generate -fcoverage-mapping" -DCMAKE_SHARED_LINKER_FLAGS="-fprofile-instr-generate -fcoverage-mapping"'

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build

      - name: Install dependencies (MacOS)
        if: matrix.target == 'Darwin'
        run: |
          brew install ninja

      - name: Build swiftshader
        run: ./${{ matrix.build_script }} ${{ matrix.cmake_args }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: swiftshader-${{ matrix.artifact }}
          path: build/${{ matrix.out_dir }}

  release:
    runs-on: ubuntu-latest
    needs: build
    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Create git tag
        id: create-git-tag
        run: |
          tag="autobuild-$(date -u '+%Y-%m-%d-%H-%M')"
          git tag $tag
          git push origin $tag
          echo "TAG=$tag" >> $GITHUB_OUTPUT
          echo "COMMIT=$(git --git-dir swiftshader/.git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Prepare artifacts
        run: |
          for target in linux64 win64 macos64 linux64-asan-coverage; do
            echo "${{ steps.create-git-tag.outputs.COMMIT }}" > swiftshader-$target/COMMIT
            tar -czf swiftshader-$target.tar.gz swiftshader-$target/*
          done

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.create-git-tag.outputs.TAG }} swiftshader-*.tar.gz \
            -n "google/swiftshader@${{ steps.create-git-tag.outputs.COMMIT }}"
