name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        target:
          - Linux
        asan:
          - false
          - true
        include:
          # --- Linux Builds ---
          - target: Linux
            asan: false
            os: ubuntu-latest
            artifact: linux64
            cmake_args: "-DSWIFTSHADER_BUILD_TESTS=OFF"

          - target: Linux
            asan: true
            os: ubuntu-latest
            artifact: linux64-asan
            # Force Clang, enable ASan
            cmake_args: "-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_FLAGS=-fsanitize=address -DCMAKE_CXX_FLAGS=-fsanitize=address -DCMAKE_SHARED_LINKER_FLAGS=-fsanitize=address -DSWIFTSHADER_BUILD_TESTS=OFF"

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies (Linux)
        if: matrix.target == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build clang

      - name: Install dependencies (MacOS)
        if: matrix.target == 'Darwin'
        run: |
          brew install ninja

      - name: Build swiftshader (Unix)
        if: matrix.target != 'Windows'
        run: |
          mkdir -p build
          cd build
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release ${{ matrix.cmake_args }} ../swiftshader
          # ONLY build the driver! This avoids all failing testing submodules.
          cmake --build . --target vk_swiftshader

      - name: Build swiftshader (Windows)
        if: matrix.target == 'Windows'
        run: |
          New-Item -ItemType Directory -ErrorAction SilentlyContinue build
          Push-Location build
          cmake ../swiftshader ${{ matrix.cmake_args }}
          # ONLY build the driver!
          cmake --build . --config Release --target vk_swiftshader
          Pop-Location

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: swiftshader-${{ matrix.artifact }}
          path: build/${{ matrix.target }}

  release:
    runs-on: ubuntu-latest
    needs: build
    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Create git tag
        id: create-git-tag
        run: |
          tag="autobuild-$(date -u '+%Y-%m-%d-%H-%M')"
          git tag $tag
          git push origin $tag
          echo "TAG=$tag" >> $GITHUB_OUTPUT
          echo "COMMIT=$(git --git-dir swiftshader/.git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Prepare artifacts
        run: |
          # Dynamically package all artifact directories
          for dir in swiftshader-*/; do
            dir="${dir%/}"
            echo "${{ steps.create-git-tag.outputs.COMMIT }}" > "$dir/COMMIT"
            tar -czf "$dir.tar.gz" "$dir"
          done

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.create-git-tag.outputs.TAG }} swiftshader-*.tar.gz \
            -n "google/swiftshader@${{ steps.create-git-tag.outputs.COMMIT }}"